stages:
  - build
  - QA
  - test

include:
  - https://raw.githubusercontent.com/fireworkweb/fwd/master/gitlab-ci/vendor.yml
  - https://raw.githubusercontent.com/fireworkweb/fwd/master/gitlab-ci/assets.yml
  - https://raw.githubusercontent.com/fireworkweb/fwd/master/gitlab-ci/eslint.yml
  - https://raw.githubusercontent.com/fireworkweb/fwd/master/gitlab-ci/phpmnd.yml
  - https://raw.githubusercontent.com/fireworkweb/fwd/master/gitlab-ci/phpcpd.yml
  - https://raw.githubusercontent.com/fireworkweb/fwd/master/gitlab-ci/php-cs-fixer.yml
  - https://raw.githubusercontent.com/fireworkweb/fwd/master/gitlab-ci/phan.yml
  - https://raw.githubusercontent.com/fireworkweb/fwd/master/gitlab-ci/phpunit.yml
  - https://raw.githubusercontent.com/fireworkweb/fwd/master/gitlab-ci/dusk.yml

assets:
  extends: .assets

vendor:
  extends: .vendor

eslint:
  extends: .eslint

security-check:
  extends: .security-check

.phpmnd:
  extends: .phpmnd

.phpcpd:
  extends: .phpcpd

php-cs-fixer:
  extends: .php-cs-fixer

phan:
  extends: .phan

phpunit:
  extends: .phpunit

dusk:
  extends: .dusk
