stages:
  - build
  - QA
  - test

variables:
  GIT_STRATEGY: fetch
  FWD_COMPOSE_EXEC_FLAGS: -T

include:
  - https://raw.githubusercontent.com/fireworkweb/fwd/1.0-rc/gitlab-ci/vendor.yml
  - https://raw.githubusercontent.com/fireworkweb/fwd/1.0-rc/gitlab-ci/assets.yml
  - https://raw.githubusercontent.com/fireworkweb/fwd/1.0-rc/gitlab-ci/eslint.yml
  - https://raw.githubusercontent.com/fireworkweb/fwd/1.0-rc/gitlab-ci/phpmnd.yml
  - https://raw.githubusercontent.com/fireworkweb/fwd/1.0-rc/gitlab-ci/phpcpd.yml
  - https://raw.githubusercontent.com/fireworkweb/fwd/1.0-rc/gitlab-ci/php-cs-fixer.yml
  - https://raw.githubusercontent.com/fireworkweb/fwd/1.0-rc/gitlab-ci/phan.yml
  - https://raw.githubusercontent.com/fireworkweb/fwd/1.0-rc/gitlab-ci/phpmd.yml
  - https://raw.githubusercontent.com/fireworkweb/fwd/1.0-rc/gitlab-ci/security-check.yml
  - https://raw.githubusercontent.com/fireworkweb/fwd/1.0-rc/gitlab-ci/dusk.yml
  - https://raw.githubusercontent.com/fireworkweb/fwd/1.0-rc/gitlab-ci/phpunit.yml

vendor:
  extends: .vendor

assets:
  extends: .assets

eslint:
  extends: .eslint

php-cs-fixer:
  extends: .php-cs-fixer

phpmd:
  extends: .phpmd

security-check:
  extends: .security-check

phpmnd:
  extends: .phpmnd

phpcpd:
  extends: .phpcpd

phan:
  extends: .phan

dusk:
  extends: .dusk

phpunit:
  extends: .phpunit
