.dusk:
  stage: test
  image: fireworkweb/dind
  services:
    - name: docker:dind
  tags:
    - dind
  script:
    - mv .env.dusk.local .env
    - bash ./fwd up -d
    - bash ./fwd artisan dusk
  after_script:
    - bash ./fwd logs http > storage/logs/nginx.log
    - bash ./fwd logs app > storage/logs/php-fpm.log
    - bash ./fwd down -v
  artifacts:
    paths:
      - storage/logs/
      - tests/Browser/screenshots
      - tests/Browser/console
    when: on_failure
    expire_in: 1 week
  variables:
    GIT_STRATEGY: fetch
    COMPOSE_EXEC_FLAGS: "-T"
  dependencies:
    - assets
    - vendor
