.phpunit:
  stage: test
  image: fireworkweb/dind
  services:
    - docker:dind
  tags:
    - dind
  script:
    - cp .env.testing .env
    - bash ./fwd up -d
    - bash ./fwd test --colors=never -vvv # --coverage-text
  after_script:
    - bash ./fwd down -v
  artifacts:
    paths:
      - storage/logs/
    when: on_failure
    expire_in: 1 week
  variables:
    GIT_STRATEGY: fetch
    COMPOSE_EXEC_FLAGS: "-T"
  dependencies:
    - assets
    - vendor
