name: build-deploy

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - uses: olegtarasov/get-tag@v1
      id: tagName

    - name: Build image
      env:
        TAGNAME: ${{ steps.tagName.outputs.tag }}
      run: docker build --pull -t fireworkweb/fwd:$TAGNAME .

    - name: Test docker image
      env:
        TAGNAME: ${{ steps.tagName.outputs.tag }}
      run: |
        docker run fireworkweb/fwd:$TAGNAME fwd -V

    - name: Push to Hub
      env:
        TAGNAME: ${{ steps.tagName.outputs.tag }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker tag fireworkweb/php:$TAGNAME fireworkweb/php:1.0-rc
        #echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        #docker push fireworkweb/php:$TAGNAME
        #docker push fireworkweb/php:1.0-rc
