name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Composer install
      uses: fireworkweb/fwd@github-actions-test
      with:
        args: fwd composer update --no-interaction --prefer-dist

    - name: PHPUnit
      uses: fireworkweb/fwd@github-actions-test
      with:
        args: fwd test --coverage-clover=coverage.xml

    services:
      dind:
        image: docker:dind
        options:
          - privileged
