name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Composer install
      uses: fireworkweb/fwd@github-actions-test
      env:
        DOCKER_HOST: "tcp://docker:${{ services.dind.ports['2375'] }}/"
      with:
        args: fwd composer update --no-interaction --prefer-dist

    - name: PHPUnit
      uses: fireworkweb/fwd@github-actions-test
      with:
        args: fwd test --coverage-clover=coverage.xml

    services:
      dind:
        image: docker:dind
        ports:
        - 2375
        options: --privileged
